//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Jack.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JackParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IJackVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_([NotNull] JackParser.Class_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDeclaration([NotNull] JackParser.PropertyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.multiPropertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiPropertyDeclaration([NotNull] JackParser.MultiPropertyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.subRoutineDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubRoutineDeclaration([NotNull] JackParser.SubRoutineDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] JackParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.subRoutineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubRoutineBody([NotNull] JackParser.SubRoutineBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] JackParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarName([NotNull] JackParser.VarNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.subRoutineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubRoutineName([NotNull] JackParser.SubRoutineNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.propertyKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyKind([NotNull] JackParser.PropertyKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.subRoutineKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubRoutineKind([NotNull] JackParser.SubRoutineKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JackParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] JackParser.TypeContext context);
}
