//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Jack.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJackListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class JackBaseListener : IJackListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.class_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_([NotNull] JackParser.Class_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.class_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_([NotNull] JackParser.Class_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.propertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyDeclaration([NotNull] JackParser.PropertyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.propertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyDeclaration([NotNull] JackParser.PropertyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.multiPropertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiPropertyDeclaration([NotNull] JackParser.MultiPropertyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.multiPropertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiPropertyDeclaration([NotNull] JackParser.MultiPropertyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubRoutineDeclaration([NotNull] JackParser.SubRoutineDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubRoutineDeclaration([NotNull] JackParser.SubRoutineDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] JackParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] JackParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubRoutineBody([NotNull] JackParser.SubRoutineBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubRoutineBody([NotNull] JackParser.SubRoutineBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassName([NotNull] JackParser.ClassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassName([NotNull] JackParser.ClassNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarName([NotNull] JackParser.VarNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarName([NotNull] JackParser.VarNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubRoutineName([NotNull] JackParser.SubRoutineNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubRoutineName([NotNull] JackParser.SubRoutineNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.propertyKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyKind([NotNull] JackParser.PropertyKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.propertyKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyKind([NotNull] JackParser.PropertyKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubRoutineKind([NotNull] JackParser.SubRoutineKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubRoutineKind([NotNull] JackParser.SubRoutineKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] JackParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] JackParser.TypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
