//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Jack.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JackParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IJackListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_([NotNull] JackParser.Class_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_([NotNull] JackParser.Class_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDeclaration([NotNull] JackParser.PropertyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDeclaration([NotNull] JackParser.PropertyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.multiPropertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiPropertyDeclaration([NotNull] JackParser.MultiPropertyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.multiPropertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiPropertyDeclaration([NotNull] JackParser.MultiPropertyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubRoutineDeclaration([NotNull] JackParser.SubRoutineDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubRoutineDeclaration([NotNull] JackParser.SubRoutineDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] JackParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] JackParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubRoutineBody([NotNull] JackParser.SubRoutineBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubRoutineBody([NotNull] JackParser.SubRoutineBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] JackParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] JackParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] JackParser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] JackParser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubRoutineName([NotNull] JackParser.SubRoutineNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubRoutineName([NotNull] JackParser.SubRoutineNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.propertyKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyKind([NotNull] JackParser.PropertyKindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.propertyKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyKind([NotNull] JackParser.PropertyKindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.subRoutineKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubRoutineKind([NotNull] JackParser.SubRoutineKindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.subRoutineKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubRoutineKind([NotNull] JackParser.SubRoutineKindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JackParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] JackParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JackParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] JackParser.TypeContext context);
}
